### ISSUE TITLE
MSBuildNuGetRestorer fails in VSTS.

### ISSUE THREAD

**Issue by johsv448** [niklaslundberg/Arbor.X#17]
When running Arbor.X in vsts_agent the step MSBuildNuGetRestorer fails. 
The reason given is:
 "Expected exactly 1 solution file, found 1
 The tool Arbor.X.Core.Tools.NuGet.MSBuildNuGetRestorer (priority=101, run always=False) failed with exit code [1, Failure]"

**Comment by niklaslundberg** [comment]
Fixed.
